FROM ubuntu

RUN apt update
#https://github.com/raspberrypi/pico-sdk instructions 
RUN DEBIAN_FRONTEND=noninteractive apt install -y g++ gcc python3 git cmake gcc-arm-none-eabi libnewlib-arm-none-eabi libstdc++-arm-none-eabi-newlib
